Cleanup firewall rules
vision-it/vision-firewall pull request #12
Opened 2019-10-06 08:17 UTC by jacksgt

https://gitlab.cc-asp.fraunhofer.de/vision-it/puppet/control/issues/169

2019-10-06 16:22 UTC, martialblog requested changes
@jacksgt I don't like having the IPs in here.

2019-10-07 08:12 UTC, jacksgt commented
Hmm, fair point.
The reason these rules are here (in pre.pp) is because they are always applied before any other rules (i.e. from Hiera), to make sure the basic communication is always functional.

But we can try moving them to Hiera.

On 6 October 2019 19:22:27 EEST, Markus Opolka <notifications@github.com> wrote:
>martialblog requested changes on this pull request.
>
>@jacksgt I don't like having the IPs in here. 
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/vision-it/vision-firewall/pull/12#pullrequestreview-297847400

2019-10-11 06:56 UTC, jacksgt commented
Done, see commit here and https://gitlab.cc-asp.fraunhofer.de/vision-it/puppet/control/merge_requests/5

2019-10-14 11:51 UTC, martialblog approved these changes

2019-10-31 09:01 UTC, merged